{
  "formatVersion": "1.1",
  "component": {
    "group": "com.teamundefined",
    "module": "defined-pedro",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.teamundefined",
          "module": "defined-core",
          "version": {
            "requires": "0.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "defined-pedro-0.3.0.aar",
          "url": "defined-pedro-0.3.0.aar",
          "size": 25023,
          "sha512": "d9d4abf49c3876c99998cc815655513fc9659326e2245a43d78f6e675d23fe773ebdb5f5fc39463ca65bc09c5aac36e62f58fb1fc45118d909bbcc4bb57809c0",
          "sha256": "df0c403048d7802899db10a519e18d1c36154c34647d003d427fd028d277d60f",
          "sha1": "8ed9e31cfc64578fda37011ca54c5e78483b4bdd",
          "md5": "038162f9bfedefe18df6e66f381a22c4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.teamundefined",
          "module": "defined-core",
          "version": {
            "requires": "0.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "defined-pedro-0.3.0.aar",
          "url": "defined-pedro-0.3.0.aar",
          "size": 25023,
          "sha512": "d9d4abf49c3876c99998cc815655513fc9659326e2245a43d78f6e675d23fe773ebdb5f5fc39463ca65bc09c5aac36e62f58fb1fc45118d909bbcc4bb57809c0",
          "sha256": "df0c403048d7802899db10a519e18d1c36154c34647d003d427fd028d277d60f",
          "sha1": "8ed9e31cfc64578fda37011ca54c5e78483b4bdd",
          "md5": "038162f9bfedefe18df6e66f381a22c4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "defined-pedro-0.3.0-sources.jar",
          "url": "defined-pedro-0.3.0-sources.jar",
          "size": 18746,
          "sha512": "3924f8d728a34cee59441fca9565a105c03f3b6e08fa8eaf902cddbe7f7e0ca0434b5aa53e32e2ffd1a656c244002d65146d84d6eafc8ac11e150e4ff5211f04",
          "sha256": "d9e798a849122f3da04767e8ecafd04bb0304c20aebe372a9b9ce0ace2f6c250",
          "sha1": "f4123631f0bb4be2b56ef08c7626b751e8798c5a",
          "md5": "c908cb7cce2c3fb3c30b271312923ba5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "defined-pedro-0.3.0-javadoc.jar",
          "url": "defined-pedro-0.3.0-javadoc.jar",
          "size": 336512,
          "sha512": "b6f6c7422b88e50699d339741a4c026f5a0e94a85f8d77316300984a165e1d06ff3e5202ff1d8ec2c5d48526e00d5eb84f3f84e8f7eac643fef1fe6c0027dadc",
          "sha256": "0c1c86c222c0f9a065d63a244d30532080ec16728a1f05fa81053ceaa6167c3e",
          "sha1": "103229cc7b486178a69808a471a0b1230a6a03bd",
          "md5": "e1eb79f430d941f4e3231bdbe445a618"
        }
      ]
    }
  ]
}
