{
  "formatVersion": "1.1",
  "component": {
    "group": "com.teamundefined",
    "module": "defined-ftc",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.teamundefined",
          "module": "defined-core",
          "version": {
            "requires": "0.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "defined-ftc-0.3.0.aar",
          "url": "defined-ftc-0.3.0.aar",
          "size": 34461,
          "sha512": "42615887cd2f915f3b971fa0c216e7545b34ef2db0e9a25b9d07eea199a16cc336cad69c8fe2ed393b542ff6f26ec32d09b082f5d4036b9d49e319b7d24e8a47",
          "sha256": "b1910babc2cf1703718a8ba4a8c2dbc442e108c6c1df12f00a2b7e240412fd3b",
          "sha1": "004d9d1a5777944b499b78088c18b749cbfd2280",
          "md5": "91822bb6f924e7800a2bce3d03722564"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.teamundefined",
          "module": "defined-core",
          "version": {
            "requires": "0.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "defined-ftc-0.3.0.aar",
          "url": "defined-ftc-0.3.0.aar",
          "size": 34461,
          "sha512": "42615887cd2f915f3b971fa0c216e7545b34ef2db0e9a25b9d07eea199a16cc336cad69c8fe2ed393b542ff6f26ec32d09b082f5d4036b9d49e319b7d24e8a47",
          "sha256": "b1910babc2cf1703718a8ba4a8c2dbc442e108c6c1df12f00a2b7e240412fd3b",
          "sha1": "004d9d1a5777944b499b78088c18b749cbfd2280",
          "md5": "91822bb6f924e7800a2bce3d03722564"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "defined-ftc-0.3.0-sources.jar",
          "url": "defined-ftc-0.3.0-sources.jar",
          "size": 23973,
          "sha512": "cbdd986518e15eebb00d74d97c162b9647af6835906775333622757cb5b49efe93c5a6d4c35b769d145110a224cf2d20bef955fa78194386657113966e1c5db1",
          "sha256": "7f6d1be2062249074af30f95c338eb4354e0db9284c724b4eeea8c8ebdd32255",
          "sha1": "8323e374ea956604d9d8e65e6edc370e91a502e7",
          "md5": "a1442b47102441321c53ac2ab4dd9aaa"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "defined-ftc-0.3.0-javadoc.jar",
          "url": "defined-ftc-0.3.0-javadoc.jar",
          "size": 350203,
          "sha512": "e11bd0a5f2e1f16b69db14f64f074b03e3f872ceaf01955c5715a0f404b8deb84c22781119b032c52684bd552c1f175cb38dc6249f8e9dce4aca6364bcc6db88",
          "sha256": "71705ff1cb82614eb759677f50767b6de01d7cca4ad3584d549d3a11aeb39e0c",
          "sha1": "e6d4b9e2b4e3c212b28e3f40b51d106e1c437e47",
          "md5": "758c11bed2fdb2ce6132e1252e2bc53a"
        }
      ]
    }
  ]
}
