{
  "formatVersion": "1.1",
  "component": {
    "group": "com.teamundefined",
    "module": "defined-pedro",
    "version": "0.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.teamundefined",
          "module": "defined-core",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "defined-pedro-0.2.1.aar",
          "url": "defined-pedro-0.2.1.aar",
          "size": 24987,
          "sha512": "d0af066f7ce1ba977815942060f9b5afc305c0a755c5bfc1b94b9a64079452225356fce5e899c61661fb973bc2f0de0a95254b43a8bd69bc49c64eee2b2c5709",
          "sha256": "27d5a2067cd91543b48aac78007e34089b31e8142b1838b501bcd882db71fee7",
          "sha1": "24359b05d0fe756251baf09cca3f47213c6842e6",
          "md5": "cfc43dea7a6138c62db48070d1bb5b66"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.teamundefined",
          "module": "defined-core",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "defined-pedro-0.2.1.aar",
          "url": "defined-pedro-0.2.1.aar",
          "size": 24987,
          "sha512": "d0af066f7ce1ba977815942060f9b5afc305c0a755c5bfc1b94b9a64079452225356fce5e899c61661fb973bc2f0de0a95254b43a8bd69bc49c64eee2b2c5709",
          "sha256": "27d5a2067cd91543b48aac78007e34089b31e8142b1838b501bcd882db71fee7",
          "sha1": "24359b05d0fe756251baf09cca3f47213c6842e6",
          "md5": "cfc43dea7a6138c62db48070d1bb5b66"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "defined-pedro-0.2.1-sources.jar",
          "url": "defined-pedro-0.2.1-sources.jar",
          "size": 18746,
          "sha512": "3924f8d728a34cee59441fca9565a105c03f3b6e08fa8eaf902cddbe7f7e0ca0434b5aa53e32e2ffd1a656c244002d65146d84d6eafc8ac11e150e4ff5211f04",
          "sha256": "d9e798a849122f3da04767e8ecafd04bb0304c20aebe372a9b9ce0ace2f6c250",
          "sha1": "f4123631f0bb4be2b56ef08c7626b751e8798c5a",
          "md5": "c908cb7cce2c3fb3c30b271312923ba5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "defined-pedro-0.2.1-javadoc.jar",
          "url": "defined-pedro-0.2.1-javadoc.jar",
          "size": 336523,
          "sha512": "4e94e021a2b7e94ec097fe8eb035b794f7f8534d719358966d57b746af10cbd6a0327e30302637f551fecdd52ef5ba4f9238b2c2951dbc0462c2d57ccdde2bce",
          "sha256": "b3a67b35f1712377518a246bef1a0425b71a1f881d9991b7824d948033bc324e",
          "sha1": "bd0caad867868aa6d6142c63fa5e2f35fa97eede",
          "md5": "24a45297f1be20514386e57ef4a9459c"
        }
      ]
    }
  ]
}
